baseurl: ''
permalink: pretty
title: 'TakeSub'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/takesub-logo-mobile.svg"
  desktop: "images/logo/takesub-logo-white.svg"
  desktop_height: "100px"

footer:
  logo: "images/logo/takesub-pwaicontrn.png"
  tech1: "images/misc/poweredbystripe-white.svg"
  copyright_text: '&copy; Copyright 2021, TakeSub'

seo:
  meta_og_title: "TakeSub"
  meta_og_type: "website"
  meta_og_url: "https://takesub.com"
  meta_og_image: "https://takesub.com/images/misc/takesub-og-image.jpg"
  meta_og_description: "TakeSub allows users to subscribe to local restaurants in Melbourne and receive signature meals, cooked by real chefs, straight to your doorsteps every fortnight."
  meta_twitter_card: "summary"
  #meta_twitter_site: "@takesub"
  #meta_twitter_creator: "@takesub"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md